name: insuranceapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  geocoder2: ^1.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  image_picker: ^0.8.7+5
  flutter_phone_direct_caller: ^2.1.1
  dialog_flowtter: ^0.3.3
  pdf: ^3.10.4
  path_provider: ^2.0.15
  printing: ^5.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  shared_preferences: ^2.1.2


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/insurancelogo.png
    - assets/images/avatar.jpg
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
